---
- hosts: debian
  become: yes
  tasks:
    - name: ping
      ping:
    # - name: command line
    #   command: "ls"

    - name: apt
      apt:
        upgrade: yes # yes or dist 
        update_cache: yes
        cache_valid_time: 360

    # Or you can have these in one line
    # - name: package
    #   package: name=nala state=present
    - name: install package
      package:
        name: 
        - tree
        - fzf
        - tmux
        - ufw
        - cifs-utils
        - s-tui
        - htop
        - curl 
        - git
        - kitty
        - docker-compose
        - stow
        - neovim
        - xsensors
        state: present

